name: lumina_gpt
description: Desktop UI for autonomous goal driven agents.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  auto_route: 6.1.0
  bloc: 8.1.1
  cupertino_icons: 1.0.2
  dart_openai: 1.9.1
  equatable: 2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.2
  freezed_annotation: 2.2.0
  get_it: 7.2.0
  injectable: 2.1.1
  isar: 3.0.5
  isar_flutter_libs: 3.0.5
  json_annotation: 4.8.0
  logger: 1.3.0
  oxidized: 5.3.0
  path_provider: 2.0.14
  window_manager: 0.3.2

dev_dependencies:
  auto_route_generator: 6.1.0
  build_runner: 2.3.3
  flutter_flavorizr: 2.1.6
  flutter_native_splash: 2.2.19
  flutter_test:
    sdk: flutter
  freezed: 2.3.2
  injectable_generator: 2.1.5
  isar_generator: 3.0.5
  json_serializable: 6.6.1
  very_good_analysis: 4.0.0+1

flavorizr:
  app:
    android:
      flavorDimensions: "app"
    ios: null

  flavors:
    development:
      app:
        name: "LuminaGPT Dev"

      android:
        applicationId: "io.killy.lumina_gpt.dev"
        generateDummyAssets: false

      ios:
        bundleId: "io.killy.lumina_gpt.dev"
        generateDummyAssets: false

    production:
      app:
        name: "LuminaGPT"

      android:
        applicationId: "io.killy.lumina_gpt"
        generateDummyAssets: false

      ios:
        bundleId: "io.killy.lumina_gpt"
        generateDummyAssets: false

flutter:
  uses-material-design: true
